### ISSUE TITLE
Add travis tests for the documentation (that is now failing)

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-wannier90#48]

**Comment by giovannipizzi** [comment]
This is the current readthedocs error:
```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/checkouts/latest/docs/source/conf.py", line 318, in <module>
    from aiida.backends import settings
ImportError: cannot import name settings


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/envs/latest/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-wannier90/checkouts/latest/docs/source/conf.py", line 318, in <module>
    from aiida.backends import settings
ImportError: cannot import name settings
```
